### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by softyoda** [neverhood311/Stop-motion-OBJ#109]
**System Information**
Operating system: Windows 10 x64

**Addon version**
Broken: (example: 2.1.0)

**Describe the bug**

Hello, i'm trying to import a ply sequence but i have this error : 

`Traceback (most recent call last):
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Stop-motion-OBJ\panels.py", line 204, in execute
    meshCount = loadSequenceFromMeshFiles(seqObj, mss.dirPath, mss.fileName)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 477, in loadSequenceFromMeshFiles
    mss.fileImporter.load(mss.fileFormat, file)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 238, in load
    self.loadPLY(filePath)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 267, in loadPLY
    bpy.ops.import_mesh.ply(filepath=filePath)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\__init__.py", line 90, in execute
    import_ply.load(self, context, path)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 428, in load
    return load_ply(filepath)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 414, in load_ply
    mesh = load_ply_mesh(filepath, ply_name)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 231, in load_ply_mesh
    obj_spec, obj, texture = read(filepath)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 223, in read
    obj = obj_spec.load(format_specs[format], plyf)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 113, in load
    return dict([(i.name, [i.load(format, stream) for j in range(i.count)]) for i in self.specs])
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 113, in <listcomp>
    return dict([(i.name, [i.load(format, stream) for j in range(i.count)]) for i in self.specs])
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 113, in <listcomp>
    return dict([(i.name, [i.load(format, stream) for j in range(i.count)]) for i in self.specs])
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 37, in load
    return [x.load(format, stream) for x in self.properties]
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 37, in <listcomp>
    return [x.load(format, stream) for x in self.properties]
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 102, in load
    return self.read_format(format, 1, self.numeric_type, stream)[0]
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_mesh_ply\import_ply.py", line 95, in read_format
    return struct.unpack(fmt, data)
struct.error: unpack requires a buffer of 4 bytes

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

`

I don't really know if it's my file that is corrupted, or the blender version (tried on 2.90 and 2.82) that is wrong.

**Comment by softyoda** [comment]
After some experiments, it work with .obj sequence, it came from the ply what was corrupted

**Comment by neverhood311** [comment]
I'm glad you figured it out.

For future generations: if you get an error while importing a mesh sequence, it's always a good idea to try importing a single mesh with the Blender importer. If you still get the same error, it's likely a problem with your file or with Blender's importer.
