### ISSUE TITLE
keyword "global_clight_size" unrecognized

### ISSUE THREAD

**Issue by hooyuser** [neverhood311/Stop-motion-OBJ#129]
**System Information**
Operating system: Windows 10

**Version**
Blender version: 2.92.0, branch: master, commit date: 2021-02-24 16:25, hash: 02948a2cab44, type: Release
Addon version: 2.1.1

I have a sequence of obj files named from 00001.obj to 00153.obj. When importing, the `file name` is specified as '0'. Other importing settings just remain default. 

It fails to import the sequence. The system console says

> Python: Traceback (most recent call last):
>   File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Stop-motion-OBJ\panels.py", line 204, in execute
>     meshCount = loadSequenceFromMeshFiles(seqObj, mss.dirPath, mss.fileName)
>   File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 477, in loadSequenceFromMeshFiles
>     fileExtension = fileExtensionFromType(_obj.mesh_sequence_settings.fileFormat)
>   File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 234, in load
>     self.loadOBJ(filePath)
>   File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 253, in loadOBJ
>     axis_forward=self.axis_forward,
>   File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
>     ret = _op_call(self.idname_py(), None, kw)
> TypeError: Converting py args to operator properties: : keyword "global_clight_size" unrecognized
> 
> location: <unknown location>:-1

I have no ideas what is going on here. Could you help solve this problem? Many thanks!

**Comment by hooyuser** [comment]
I'm aware that I didn't type the folder name correctly. A stupid mistake :)
