### ISSUE TITLE
OBJ import fails in Blender 4.0.0 alpha

### ISSUE THREAD

**Issue by acyc070** [neverhood311/Stop-motion-OBJ#178]
it's shows this:
Python: Traceback (most recent call last):
  File "C:\Users\z\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Stop-motion-OBJ\panels.py", line 300, in execute
    meshCount = loadSequenceFromMeshFiles(seqObj, mss.dirPath, mss.fileName)
  File "C:\Users\z\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 786, in loadSequenceFromMeshFiles
    mss.fileImporter.load(mss.fileFormat, file)
  File "C:\Users\z\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 415, in load
    self.loadOBJ(filePath)
  File "C:\Users\z\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 444, in loadOBJ
    bpy.ops.import_scene.obj(
  File "C:\Users\z\Downloads\blender-4.0.0-alpha+main.d8e4fe320784-windows.amd64-release\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
AttributeError: Calling operator "bpy.ops.import_scene.obj" error, could not be found

**Comment by neverhood311** [comment]
Since Blender 4.0.0 is still in the Alpha phase and its feature set and API are subject to change, I'm not yet worried about making Stop Motion OBJ compatible with 4.0.0. Once the 4.0.0 Beta version is released, we can reopen this if it's still a problem.
