### ISSUE TITLE
Multiple Errors When Trying to Import Mesh Sequence

### ISSUE THREAD

**Issue by jessekirbs** [neverhood311/Stop-motion-OBJ#179]
**System Information**
Windows 10

**Addon version**
Broken: 2.1.1

**Describe the bug**
When I try to import a PLY mesh sequence, I receive the following console errors:
`Python: Traceback (most recent call last):
  File "C:\Users\Cybersurf\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Stop-motion-OBJ\panels.py", line 204, in execute
    meshCount = loadSequenceFromMeshFiles(seqObj, mss.dirPath, mss.fileName)
  File "C:\Users\Cybersurf\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 493, in loadSequenceFromMeshFiles
    mss.fileImporter.load(mss.fileFormat, file)
  File "C:\Users\Cybersurf\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 238, in load
    self.loadPLY(filePath)
  File "C:\Users\Cybersurf\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Stop-motion-OBJ\stop_motion_obj.py", line 283, in loadPLY
    bpy.ops.import_mesh.ply(filepath=filePath)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_mesh_ply\__init__.py", line 80, in execute
    import_ply.load(self, context, path)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_mesh_ply\import_ply.py", line 435, in load
    return load_ply(filepath)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_mesh_ply\import_ply.py", line 417, in load_ply
    mesh = load_ply_mesh(filepath, ply_name)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_mesh_ply\import_ply.py", line 358, in load_ply_mesh
    mesh.loops.foreach_set("vertex_index", loops_vert_idx)
TypeError: couldn't access the py sequence
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113
`

**Steps To Reproduce**
1. Go to File > Import > Mesh Sequence
2. Change 'file type' to 'PLY'
3. Type first few letters of the PLY sequence filenames.
4. Click 'Select Folder'
5. Receive console errors.

**Expected behavior**
The PLY sequence should import and be playable from the timeline.

**Comment by neverhood311** [comment]
Can you share a few meshes from your sequence? I just tried importing PLY files into Blender 3.6 with version 2.1.1 of the addon and it worked just fine.
