### ISSUE TITLE
Can't import OBJ sequence - Blender 3.2/4.0

### ISSUE THREAD

**Issue by jochemmessmer** [neverhood311/Stop-motion-OBJ#187]
**System Information**
Operating system:
Mac OSX

**Addon version**
Broken: (example: 2.1.1)

**Describe the bug**
Python: Traceback (most recent call last):
  File "/Users/jochemmessmer/Library/Application Support/Blender/4.0/scripts/addons/Stop-motion-OBJ/panels.py", line 304, in execute
    
  File "/Users/jochemmessmer/Library/Application Support/Blender/4.0/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 763, in loadStreamingSequenceFromMeshFiles
    def removeMeshFromCache(obj, meshIdx):
  File "/Users/jochemmessmer/Library/Application Support/Blender/4.0/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 1022, in setFrameObjStreamed
    # update the frame so the right shape is visible
  File "/Users/jochemmessmer/Library/Application Support/Blender/4.0/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 1078, in importStreamedFile
  File "/Users/jochemmessmer/Library/Application Support/Blender/4.0/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 415, in load
    
  File "/Users/jochemmessmer/Library/Application Support/Blender/4.0/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 444, in loadOBJ
    def loadStreamingSequenceFromMeshFiles(obj, directory, filePrefix):
  File "/Applications/Blender 4.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
AttributeError: Calling operator "bpy.ops.import_scene.obj" error, could not be found

First it worked, but now I get this error, how to fix? :) Same problems in blender 3.2

**Comment by neverhood311** [comment]
Stop Motion OBJ does not support Blender 4.0. You'll need to use Blender 3.6

**Comment by jochemmessmer** [comment]
Hey, thanks for the quick reply. That did the trick. Next problem is that the .mtl files are not put on the OBJ sequence, is it possible to achieve that? Will close this thread afterwards..
