### ISSUE TITLE
Unable to use due to errors.

### ISSUE THREAD

**Issue by NicTanghe** [neverhood311/Stop-motion-OBJ#50]
Traceback (most recent call last):
  File "/home/tanghe/.config/blender/2.82/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 514, in execute
    obj = MSC.newMeshSequence()
  File "/home/tanghe/.config/blender/2.82/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 147, in newMeshSequence
    bpy.ops.object.add(type='MESH')
  File "/usr/share/blender/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.add.poll() failed, context is incorrect

location: <unknown location>:-1

i`m using linux on arch.

**Comment by NicTanghe** [comment]
Still had other geo selected.
