### ISSUE TITLE
Error when enabling addon on blender 2.83

### ISSUE THREAD

**Issue by koerismo** [neverhood311/Stop-motion-OBJ#83]
**System Information**
Operating system: Windows 10

**Addon version**
2.0.2

**Describe the bug**
Spits out this when I attempt to enable the addon:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Stop-motion-OBJ-2'

```

**Steps To Reproduce**
Attempt to enable the addon in blender 2.83

**Expected behavior**
I just wanted to enable the addon

**Screenshots**
![image](https://user-images.githubusercontent.com/56563658/85934590-a62edd00-b8b2-11ea-9600-3d75c54eaa7d.png)

**Comment by neverhood311** [comment]
Make sure you're downloading the right .zip file. You want to download the file in the release notes, not the "Source code (.zip)" file:

![smo_correct_downloadJPG](https://user-images.githubusercontent.com/4615170/85935916-04f45680-b8b3-11ea-97e4-831064c968f3.JPG)

**Comment by koerismo** [comment]
When I did the same thing in blender 2.82 it worked. (There were errors later but I’ll make an issue if they continue)

**Comment by neverhood311** [comment]
Did you make sure you're downloading the correct file? The ones labeled "Source code" are not the right files.

**Comment by StephenMcAvoy** [comment]
I had problems installing V 2.0.2 in Blender 2.83 from the zip file. After restarting Blender, Stop motion could be found in preferences but not in File > import
When I tried installing it manually I messed up the Blender 2.8.3 installation and have gone back to Blender 2.8.

**Comment by neverhood311** [comment]
In 2.83, add-ons should be installed in the `%appdata%\Roaming\Blender Foundation\2.83\scripts\addons` folder. If you navigate there, what do you see? If there are any `Stop-motion-OBJ` folders, try deleting those. Also go to `C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons` and delete anything related to Stop-motion-OBJ. Then try reinstalling the addon using the .zip file.

If all else fails, just use v2.1.0 instead of v2.0.2 since it's no longer supported.

**Comment by StephenMcAvoy** [comment]
Last things first.
It is the correct version, I took the text from Blender as I’ve too many Betas to count. ;) Would you check the version displayed in Blender Preferences, please?
As for installing it in the latest version of Blender. I still have problems and I have had to do 3 System Restores.
 I’ve stopped for the moment while I think. I did not un-install Ver 2.8 so both were in the registry. :(
What I did see was that the folders: 
Stop- motion-OBJ; 
Stop- motion-OBJ -0.2.79.2; 
Stop- motion-OBJ -2.0.0 in 
AppData > Roaming > BlenderFoundation > Blender > 2.83 > scripts > addons

The last time I tried to install Stop_motion in 2.83 it seemed to install but when I tried to activate it. I got the errors:

Traceback (most recent call last):
File "C:\Proglam Files\Blender Foundation\Blender 2.83\2.83\Scripts\modules\addon_utils.py", line 351, in enable
mod = _import_(module_name)
ModuleNotFoundError: No module named 'Stop-motion-OBJ-2'

**Comment by neverhood311** [comment]
I think I've seen this issue before. I don't remember what caused it, but it should be sufficient to delete those three Stop-motion-OBJ folders and re-install the addon.

**Comment by neverhood311** [comment]
Closing due to inactivity
